AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
# Description: >
#   dmarc-rua-report-searcher
Parameters:
  MyDomain:
    Type: String
  MailUser:
    Type: String


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
Resources:
  RuaConverterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: report_converter/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - arm64
      Events:
        BucketMailConverter:
          Type: S3
          Properties:
            Bucket: !Ref MailBucket
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Sub source/
      Policies:
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource: !Sub arn:aws:s3:::${MyDomain}-mail-stocker/source/*
            - Effect: Allow
              Action: s3:PutObject
              Resource: !Sub arn:aws:s3:::${MyDomain}-mail-stocker/output/*
  # ----------------------------------
  # ---- Amazon SES
  # ----------------------------------
  RuleSet:
    Type: AWS::SES::ReceiptRuleSet
    Properties: 
      RuleSetName: !Sub ${MyDomain}-rua-receiver-ruleset
  RuleDetail:
    Type: AWS::SES::ReceiptRule
    Properties: 
      RuleSetName: !Ref RuleSet
      Rule: 
        Name: !Sub ${MailUser}_${MyDomain}
        Recipients: 
          - !Sub ${MailUser}@${MyDomain}
        Enabled: True
        TlsPolicy: Require
        ScanEnabled: True
        Actions:
          - S3Action:
              BucketName: !Ref MailBucket
              ObjectKeyPrefix: !Sub source/${MailUser}
  # ----------------------------------
  # ---- Amazon S3
  # ----------------------------------
  MailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${MyDomain}-mail-stocker
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: True
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  MailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MailBucket
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Sid: AllowPutFromSES
            Effect: Allow
            Principal: 
              Service: ses.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${MailBucket}/source/*
            Condition: 
              StringEquals: 
                aws:Referer: !Ref AWS::AccountId